name: Deploy to AWS EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリチェックアウト
        uses: actions/checkout@v4

      - name: AWS認証
        uses: aws-actions/configure-aws-credentials@v2
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_SCCESS_KEY }}
           aws-region: ap-northeast-1 #東京リージョンを指定
        
      - name: S3にアップロード
        run:
          aws s3 sync ./web/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete